### ISSUE TITLE
support for args + lambda arg

### ISSUE THREAD

**Issue by francescoagati** [ciscoheat/slambda#1]
in some cases as d3 library the function callback is added after some params. 
for example 

```
d3.attr("y", function(d, i) { return i * barHeight; })
```

wit slambda i can't write this with using

```
  d3.attr.fn("y",[d,i] => i * barHeight)
```

but this 

```
  d3.attr("y", fn([d,i] => return i * barHeight))
```

**Comment by ciscoheat** [comment]
Hello, yes there is no lambda syntax detection for the rest arguments, only the first one. It's no problem to add, but I'm trying to consider all special cases for doing that.

When using the arrow syntax everything is fine, but with the autodetection of `_`, `_1`, etc, things can get complicated. I'm considering that if no underscore parameter is found, the expression is returned as-is.

A downside is that it will make the library a bit less intuitive to use, because this could be easy to forget. I will make some tests, and if you have any suggestions, let me know!

**Comment by francescoagati** [comment]
i don't know if with getExpectedType  http://api.haxe.org/haxe/macro/Context.html#getExpectedType is possible to get the params of the function call.

**Comment by ciscoheat** [comment]
Thanks, I'll make some tests!

**Comment by ciscoheat** [comment]
Should work now with the latest commit. Thanks for the motivation to clean things up as well. :)

**Comment by francescoagati** [comment]
Thanks to you. i have implemented a short lambda for thx.core but yours is really fantastic.
You could merge the code of slambda inside thx.core replace my implementation? what do you think?

**Comment by ciscoheat** [comment]
Thank you. :) Sure, I can add it if that's fine with you. Where is it located in thx.core?

**Comment by francescoagati** [comment]
i have send to you an invite for the gitter chat of thx.core so we can speak about this with Franco.
The code of thx.core is here.

https://github.com/fponticelli/thx.core
